include:
 - board: seeeduino_xiao_rp2040
   shield: qaz_ble
   snippet: studio-rpc-usb-uart
   cmake-args: -DCONFIG_ZMK_STUDIO=y
 - board: seeeduino_xiao_ble
   shield: qaz_ble
   snippet: studio-rpc-usb-uart
   cmake-args: -DCONFIG_ZMK_STUDIO=y
 - board: seeeduino_xiao_rp2040
   shield: qaz_num_ble
   snippet: studio-rpc-usb-uart
   cmake-args: -DCONFIG_ZMK_STUDIO=y
 - board: seeeduino_xiao_ble
   shield: qaz_num_ble
   snippet: studio-rpc-usb-uart
   cmake-args: -DCONFIG_ZMK_STUDIO=y